-- Modelo Oracle para Soporte Valex (doc sección 14.2)
-- Puntos 4 (workflows/aprobaciones) y 6 (ingesta documental).

-- ---- Punto 4: Workflow y aprobaciones ----
CREATE TABLE WF_EXECUTION (
    EXECUTION_ID  VARCHAR2(64)  PRIMARY KEY,
    SESSION_ID    VARCHAR2(64)  NOT NULL,
    STATUS        VARCHAR2(32)  NOT NULL,
    STEP          NUMBER        DEFAULT 0,
    STARTED_AT    TIMESTAMP     DEFAULT SYSTIMESTAMP,
    UPDATED_AT    TIMESTAMP     DEFAULT SYSTIMESTAMP
);

CREATE TABLE WF_APPROVAL (
    APPROVAL_ID   VARCHAR2(64)  PRIMARY KEY,
    EXECUTION_ID  VARCHAR2(64)  NOT NULL,
    APPROVAL_TYPE VARCHAR2(32)  NOT NULL,
    APPROVER      VARCHAR2(128),
    DECISION      VARCHAR2(16),
    CREATED_AT    TIMESTAMP     DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_APPROVAL_EXEC FOREIGN KEY (EXECUTION_ID)
        REFERENCES WF_EXECUTION (EXECUTION_ID)
);

CREATE TABLE WF_CHECKPOINT (
    CHECKPOINT_ID VARCHAR2(64)  PRIMARY KEY,
    EXECUTION_ID  VARCHAR2(64)  NOT NULL,
    STEP          NUMBER        NOT NULL,
    HISTORY_JSON  CLOB,
    CREATED_AT    TIMESTAMP     DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_CHECKPOINT_EXEC FOREIGN KEY (EXECUTION_ID)
        REFERENCES WF_EXECUTION (EXECUTION_ID)
);

-- ---- Punto 6: Ingesta documental y embeddings ----
CREATE TABLE KB_DOCUMENT (
    DOCUMENT_ID   VARCHAR2(64)  PRIMARY KEY,
    FILE_NAME     VARCHAR2(512) NOT NULL,
    VERSION       VARCHAR2(32),
    SOURCE        VARCHAR2(128),
    CREATED_AT    TIMESTAMP     DEFAULT SYSTIMESTAMP
);

CREATE TABLE KB_CHUNK (
    CHUNK_ID      VARCHAR2(64)  PRIMARY KEY,
    DOCUMENT_ID   VARCHAR2(64)  NOT NULL,
    CHUNK_ORDER   NUMBER        NOT NULL,
    CHUNK_TEXT    CLOB,
    CREATED_AT    TIMESTAMP     DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_CHUNK_DOC FOREIGN KEY (DOCUMENT_ID)
        REFERENCES KB_DOCUMENT (DOCUMENT_ID)
);

CREATE TABLE KB_EMBEDDING (
    EMBEDDING_ID  VARCHAR2(64)  PRIMARY KEY,
    CHUNK_ID      VARCHAR2(64)  NOT NULL,
    VECTOR_REF    VARCHAR2(256),
    MODEL_NAME    VARCHAR2(128),
    CREATED_AT    TIMESTAMP     DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_EMBED_CHUNK FOREIGN KEY (CHUNK_ID)
        REFERENCES KB_CHUNK (CHUNK_ID)
);
